<%@ Page Title="" Language="C#" MasterPageFile="~/Site.Master" AutoEventWireup="true" CodeBehind="ProductList.aspx.cs" Inherits="ZobShop.Web.Administration.ProductList" %>

<asp:Content ID="Content1" ContentPlaceHolderID="MainContent" runat="server">
    <asp:GridView runat="server" ID="Products"
        AutoGenerateColumns="True"
        AutoGenerateEditButton="True"
        AutoGenerateDeleteButton="True">
    </asp:GridView>
</asp:Content>
