<%@ Page Title="" Language="C#" MasterPageFile="~/Site.Master" AutoEventWireup="true" CodeBehind="UserList.aspx.cs" Inherits="ZobShop.Web.Administration.UserList" %>

<asp:Content ID="Content1" ContentPlaceHolderID="MainContent" runat="server">
    <asp:GridView runat="server"
        ID="UsersList"
        AutoGenerateColumns="True"
        AutoGenerateDeleteButton="True"
        AutoGenerateEditButton="True">
    </asp:GridView>
</asp:Content>
